In [ ]:
import numpy as np
import random as rndm
import time

<h1>make gene</h1>

In [ ]:
population=list()
best_solution=int(1e18)
best_solution_index=0

def make_gene(initial=[0]*9):

    mapp={}

    gene=list(range(1,10))
    rndm.shuffle(gene)#making a gene and random it to be random from 1:9

    for i in range(9):
        mapp[gene[i]]=i#maping the gene to its index to be known

    for i in range(9):
        if initial[i]!=0 and gene[i]!=initial[i]:

            temp=gene[i],gene[mapp[initial[i]]]

            gene[mapp[initial[i]]],gene[i]=temp#swaping

            mapp[initial[i]],mapp[temp[0]]=i,mapp[initial[i]]#update the map

    return gene



<h1>make chromosome</h1>

In [ ]:
def make_chromosome(initial=[[0]*9]*9):
    chromosome=[]
    for i in range(9):
        chromosome.append(make_gene(initial[i]))
    return chromosome



<h1>make population</h1>

In [ ]:
def make_population(count,initial=[[0]*9]*9):
    population.clear()
    for _ in range(count):
        population.append(make_chromosome(initial))


In [ ]:
def get_fitness(chromosome):
    fitness=0
    for i in range(9):
        seen={}
        for j in range(9):
            if chromosome[j][i] in seen:
                seen[chromosome[j][i]]+=1
            else:
                seen[chromosome[j][i]]=1
        for key in seen:
            fitness+=(seen[key]-1)
    for m in range(3):
        for n in range(3):
            seen={}
            for i in range((3*n),3*(n+1)):
                for j in range(3*(m),3*(m+1)):
                    if chromosome[j][i] in seen:
                        seen[chromosome[j][i]]+=1
                    else:
                        seen[chromosome[j][i]]=1
            for key in seen:
                fitness+=(seen[key]-1)

    return fitness

# x=make_population(1)
# for i in range(9):
#     for j in range(1):
#         print(x[0][i][j],x[0][i][j+1],x[0][i][j+2],'|',x[0][i][j+3],x[0][i][j+4],x[0][i][j+5],'|',x[0][i][j+6],x[0][i][j+7],x[0][i][j+8])
#     if((i+1)%3==0 and i!=8):print('-'*5,'+','-'*5,'+','-'*5)

# print()

# print('fitness :',get_fitness(x[0]))

In [ ]:
def flatten(lst):
    flst=[]
    for x in lst:
        for y in x:
            flst.append(y)
    return flst

def mutation(chromsome,chromsome_index,mutation_factor):
    target_vector=flatten(chromsome)

    target_vector=np.array(target_vector)

    idxs = [idx for idx in range(len(population)) if idx != chromsome_index]

    random_vectors=[]#a,b,c vectors

    for i in (np.random.choice(idxs, 3, replace = False)):
        random_vectors.append(flatten(population[i]))


    for i in range(len(random_vectors)):
        random_vectors[i]=np.array(random_vectors[i])

    donor_vector=np.clip(random_vectors[0]+mutation_factor*(random_vectors[1]-random_vectors[2]),1,9)

    return donor_vector

# pop=make_population(4)
# print(mutation(pop,pop[0],0,1))

In [ ]:
def recombination(donor_vector,target_vector,cross_probability):
    cross_points=np.random.rand(81)<=cross_probability

    if not np.any(cross_points):
        cross_points[np.random.randint(0,81)]=True

    #trial_vector=np.where(cross_points,donor_vector,target_vector)
    cnt=0
    trial_vector=[]
    hap = {}
    for i in range(9):#row
        mapp={}
        for j in range(9):#col
            if org[cnt]==1 :
              trial_vector.append(ans[cnt])
              mapp[ans[cnt]] = 1
              hap[ans[cnt]] = 1
            elif(cross_points[cnt]==True and mapp[donor_vector[cnt]]!=1):
                trial_vector.append(donor_vector[cnt])
                mapp[donor_vector[cnt]]=1
            elif(cross_points[cnt]==False and mapp[target_vector[cnt]]!=1):
                trial_vector.append(target_vector[cnt])
                mapp[target_vector[cnt]]=1
            else:
                for ind in range(1,9):
                    if(mapp[ind]!=1):
                        trial_vector.append(ind)
                        mapp[ind]=1
                        break

    return trial_vector

# pop=make_population(4)
# donor_vector=mutation(pop,pop[0],0,1)
# trial_vector=(recombination(donor_vector,np.asarray(flatten(pop[0])),0.5))
# trial_vector=trial_vector.reshape((9,9))

IndentationError: ignored

In [ ]:

def selection(trial_vector,target_vector,chromosome_index):
    global best_solution_index,best_solution

    if(get_fitness(trial_vector)<get_fitness(target_vector)):
        population[chromosome_index]=trial_vector

    gt_fit=get_fitness(population[chromosome_index])
    if gt_fit <= best_solution:
        best_solution=gt_fit
        best_solution_index=chromosome_index

# pop=make_population(4)
# donor_vector=mutation(pop,pop[0],0,1)
# trial_vector=(recombination(donor_vector,np.asarray(flatten(pop[0])),0.5))
# trial_vector=trial_vector.reshape((9,9))

In [ ]:
puzzle=[[8,0,6,0,0,0,1,0,7],
        [0,0,0,6,0,2,0,0,0],
        [0,5,3,0,0,4,8,0,6],
        [7,0,4,8,0,0,6,3,0],
        [0,0,0,0,0,0,0,9,0],
        [1,0,0,5,0,0,4,0,0],
        [0,0,1,2,0,0,7,0,9],
        [2,0,0,0,9,6,0,0,0],
        [0,7,0,0,1,0,0,8,0]
        ]

org={}
ans = {}
c=0
for i in range(9):
        for j in range(9):
                if(puzzle[i][j]!=0):
                        org[c]=1
                        ans[c]=puzzle[i][j]
                c+=1

[[8 9 6 1 9 7 1 2 7]
 [9 1 7 6 7 2 9 6 9]
 [8 5 3 9 8 4 8 1 6]
 [7 9 4 8 1 9 6 3 5]
 [3 5 5 5 3 5 1 9 8]
 [1 2 6 5 6 2 4 7 9]
 [5 6 1 2 8 7 7 9 9]
 [2 3 8 3 9 6 7 6 2]
 [5 7 9 4 1 5 5 8 4]]

population_size=500
iterations=100
make_population(population_size,puzzle)

for its in range(iterations):
        stop_criteria=False
        for pop in range(len(population)):

                donor_vector=mutation(population[pop],pop,1)
                trial_vector=recombination(donor_vector,np.array(flatten(population[pop])),0.5)
                selection(trial_vector.reshape((9,9)),np.array(flatten(population[pop])).reshape((9,9)),pop)

                if(get_fitness(population[best_solution_index])==0):
                        stop_criteria=True
                        break

        print('iteration_number :',its)
        print('best_solution:',get_fitness(population[best_solution_index]))
        if(stop_criteria==True):
                break

print('best_solution\n',best_solution_index,' ',np.array(population[best_solution_index]))
print()
print('fitness_function\n',get_fitness(population[best_solution_index]))

iteration_number : 0
best_solution: 34
iteration_number : 1
best_solution: 34
iteration_number : 2
best_solution: 34
iteration_number : 3
best_solution: 34
iteration_number : 4
best_solution: 34
iteration_number : 5
best_solution: 34
iteration_number : 6
best_solution: 34
iteration_number : 7
best_solution: 34
iteration_number : 8
best_solution: 34
iteration_number : 9
best_solution: 34
iteration_number : 10
best_solution: 34
iteration_number : 11
best_solution: 34
iteration_number : 12
best_solution: 34
iteration_number : 13
best_solution: 34
iteration_number : 14
best_solution: 33
iteration_number : 15
best_solution: 33
iteration_number : 16
best_solution: 33
iteration_number : 17
best_solution: 33
iteration_number : 18
best_solution: 33
iteration_number : 19
best_solution: 33
iteration_number : 20
best_solution: 33
iteration_number : 21
best_solution: 33
iteration_number : 22
best_solution: 33
iteration_number : 23
best_solution: 33
iteration_number : 24
best_solution: 33
iteration_